// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buiaaanpmfaaehklyfla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aWFhYW5wbWZhYWVoa2x5ZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMzUzMjEsImV4cCI6MjA1MTcxMTMyMX0.aaEIasOVG2kK3MhOzVXzuxq9sldKUwa8dL2CBm4VoDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);